language: python
dist: xenial
sudo: true

python:
    - "3.5"
    - "3.6"
    - "3.7"

services:
    - redis-server


install:
    - pip install -e .[tests]

script:
    - pytest -v --cov=spinach tests/
    - pycodestyle --ignore=E252,W503,W504 spinach tests

after_success:
  - pip install python-coveralls
  - coveralls

notifications:
    email: false
